export const UPDATE_USER_FRIENDS = "UPDATE_USER_FRIENDS";

export const UPDATE_USER_GAMES = "UPDATE_USER_GAMES";
export const COMPARE_FRIENDS = 'COMPARE_FRIENDS'
export const COMPARE_GAMES = 'COMPARE_GAMES'

